<?php

<{namespace}>

use app\Request;
<{use}>
/**
 * <{classComment}>
 * Class <{className}>
 * @package <{package}>
 */
class <{className}> extends BaseAdminApiController
{

   /**
    * 初始化
    */
   public function initialize()
   {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new <{className}>Service();
   }

   /**
    * <{notes}>列表
    * @param Request $request
    * @return \think\response\Json
    */
    public function list(Request $request)
    {
        $data = $request->params([
<{searchParam}>
        ]);
        return success($this->service->getList($data));
    }

    /**
     * <{notes}>详情
     * @param int $id (<{notes}>id)
     * @return \think\response\Json
     */
    public function info(int $id)
    {
        return success($this->service->getInfo($id));
    }

    /**
     * <{notes}>添加
     * @param Request $request
     * @return \think\response\Json
     */
    public function add(Request $request)
    {
        $data = $request->params(<{addParam}>);
        $this->validate($data, '<{validate}>.add');
        $id = $this->service->add($data);
        if($id)
        {
            return success('添加成功', ['id' => $id]);
        }
        return error('添加失败');
    }

    /**
     * <{notes}>编辑
     * @param int $id (<{notes}>id)
     * @return \think\response\Json
     */
    public function edit(Request $request, int $id)
    {
        $data = $request->params(<{editParam}>);
        $this->validate($data, '<{validate}>.edit');
        if($this->service->edit($id, $data))
        {
            return success('保存成功');
        }
        return error('保存失败');
    }

    /**
     * <{notes}>删除 支持批量删除
     * @param string $id (<{notes}>ids)
     * @return \think\response\Json
     */
    public function delete(string $ids){
        $res = $this->service->delete($ids);
        if($res)
        {
        return success('删除成功', $res);
        }
        return error('删除失败');
    }

    <{with}>
}
