<?php

namespace core\src\http\controller\admin\file;


use core\base\controller\BaseAdminApiController;

/**
 * 文件管理控制器
 * Class File
 * @package app\admin\controller\system
 */
class FileGroup extends BaseAdminApiController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function groupList () {

    }

    public function list () {

    }

    public function delete (string $ids) {

    }
}