<?php

namespace app\admin\controller\addon;


use app\Request;
use core\base\BaseAdminController;
use core\lib\addon\AddonDevelopService;
use think\Response;


/**
 * 开发插件控制器
 * Class AddonDevelop
 * @package app\admin\controller\addon
 */
class AddonDevelop extends BaseAdminController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new AddonDevelopService();
    }

    /**
     * 插件类型
     * @return Response
     */
    public function type(){
        return success([
            'app'   => '应用',
            'addon' => '插件',
        ]);
    }

    /**
     * 开发插件列表
     * @return \think\response\Json
     */
    public function lists()
    {
        $data = $this->request->params([
            ['search', '']
        ]);
        return success($this->service->getList($data['search']));
    }

    /**
     * 开发插件详情
     * @param $key
     * @return \think\response\Json
     */
    public function info($key)
    {
        return success((new AddonDevelopService())->getInfo($key));
    }

    /**
     * 开发插件新增
     * @param string $key
     * @return \think\response\Json
     */
    public function add(Request $request, string $key)
    {
        $data = $request->params([
            ['title', ''],
            ['desc', ''],
            ['icon', ''],
            ['cover', ''],
            ['key', ''],
            ['author', ''],
            ['version', ''],
            ['type', ''],
            ['support_app', ''],
        ], false);
        $data['key'] = $key;
        $this->validate($data, 'app\validate\addon\AddonDevelop.add');
        (new AddonDevelopService())->add($data);
        return success('ADD_SUCCESS');
    }

    /**
     * 开发插件更新
     * @param string $key
     * @return \think\response\Json
     */
    public function edit(Request $request, string $key)
    {
        $data = $request->params([
            ['title', ''],
            ['desc', ''],
            ['icon', ''],
            ['cover', ''],
            ['key', ''],
            ['author', ''],
            ['version', ''],
            ['type', ''],
            ['support_app', ''],
        ], false);
        $data['key'] = $key;
        $this->validate($data, 'app\validate\addon\AddonDevelop.edit');
        (new AddonDevelopService())->edit($key, $data);
        return success('EDIT_SUCCESS');
    }

    /**
     * 删除开发插件
     * @param string $key
     * @return \think\response\Json
     */
    public function del(string $key)
    {
        (new AddonDevelopService())->delete($key);
        return success('DELETE_SUCCESS');
    }

    /**
     *校验key是否被占用
     * @param $key
     * @return void
     */
    public function checkKey($key){
        return success(data:(new AddonDevelopService())->checkKey($key));
    }

    /**
     * 打包
     * @param $key
     * @return Response
     */
    public function build($key){
        (new AddonDevelopService())->build($key);
        return success();
    }

    /**
     * 下载
     * @param $key
     * @return Response
     */
    public function download($key){

        return success(data:(new AddonDevelopService())->download($key));
    }

}
