<?php

namespace core\src\addon\auth\src\admin\controller\auth;

use app\Request;
use app\service\admin\auth\RoleService;
use core\base\controller\BaseAdminApiController;

/**
 * 角色控制器
 * Class Role
 * @package core\src\addon\auth\src\admin\controller\auth
 */
class Role extends BaseAdminApiController
{

   /**
    * 初始化
    */
   public function initialize()
   {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new RoleService();
   }

   /**
    * 角色列表
    * @param Request $request
    * @return \think\response\Json
    */
    public function list(Request $request)
    {
        $data = $request->params([
             ["parent_id", ""], 
             ["name", ""], 
             ["code", ""], 
             ["description", ""], 
             ["rules", ""], 
             ["status", ""]
        ]);
        return success($this->service->getList($data));
    }

    /**
     * 角色详情
     * @param int $id (角色id)
     * @return \think\response\Json
     */
    public function info(int $id)
    {
        return success($this->service->getInfo($id));
    }

    /**
     * 角色添加
     * @param Request $request
     * @return \think\response\Json
     */
    public function add(Request $request)
    {
        $data = $request->params([
             ["parent_id", 0], 
             ["name", ""], 
             ["code", ""], 
             ["description", ""], 
             ["rules", ""], 
             ["status", ""], 

        ]);
        $this->validate($data, 'app\validate\auth\Role.add');
        $id = $this->service->add($data);
        if($id)
        {
            return success('添加成功', ['id' => $id]);
        }
        return error('添加失败');
    }

    /**
     * 角色编辑
     * @param int $id (角色id)
     * @return \think\response\Json
     */
    public function edit(Request $request, int $id)
    {
        $data = $request->params([
             ["parent_id", 0], 
             ["name", ""], 
             ["code", ""], 
             ["description", ""], 
             ["rules", ""], 
             ["status", ""], 

        ]);
        $this->validate($data, 'app\validate\auth\Role.edit');
        if($this->service->edit($id, $data))
        {
            return success('保存成功');
        }
        return error('保存失败');
    }

    /**
     * 角色删除 支持批量删除
     * @param string $id (角色ids)
     * @return \think\response\Json
     */
    public function delete(string $ids){
        $res = $this->service->delete($ids);
        if($res)
        {
        return success('删除成功', $res);
        }
        return error('删除失败');
    }

    
}
